ci:
  preset: perf
  collect:
    url: http://localhost:4173
    numberOfRuns: 1
  assert:
    assertions:
      "categories:performance": ['warn', {"minScore": 0.50}]
      "categories:accessibility": ['error', {"minScore": 0.90}]
      "categories:best-practices": ['error', {"minScore": 0.70}]
      "categories:seo": ['error', {"minScore": 0.80}]
      "first-contentful-paint": ["warn", {"minScore": 0.50}]
      "largest-contentful-paint": ["warn", {"minScore": 0.01}]
      "legacy-javascript": ["warn", {}]
      "render-blocking-resources": ["warn", {}]
      "interactive": ["warn", {"minScore": 0.50}]
      "uses-long-cache-ttl": ["off", {}]
      "render-blocking-insight": ["off", {}]
      "max-potential-fid": ["warn", {"minScore": 0.50}]
      "modern-image-formats": ["warn", {}]
      "cache-insight": ["warn", {}]
