import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { saveAs } from 'file-saver';
import { PracticeSession as Session } from '../types/session';
import { format, parseISO } from 'date-fns';
import logger from './logger';

// A more specific type for the internal, undocumented API
interface jsPDFInternal {
  getNumberOfPages: () => number;
  pageSize: {
    height: number;
    width: number;
  };
}

import { toast } from '@/lib/toast';

const formatOptionalNumber = (value: number | null | undefined, formatter: (value: number) => string, fallback = 'N/A') =>
  typeof value === 'number' ? formatter(value) : fallback;

const getFillerTableData = (fillerWords: Session['filler_words']) =>
  Object.entries(fillerWords || {})
    .filter(([word]) => word !== 'total')
    .map(([word, data]) => [word, data.count]);

const formatEngineLabel = (session: Session): string => {
  const mode = session.engine || 'Unknown';
  const details = [session.model_name, session.engine_version, session.device_type].filter(Boolean);
  return details.length > 0 ? `${mode} (${details.join(', ')})` : mode;
};

export const generateSessionPdf = async (session: Session, username: string = 'User', _isPro: boolean = false) => {
  const identifier = username && username !== 'User' ? username : session.user_id;

  try {
    toast.info("Generating PDF...", { id: 'pdf-gen' });
    const doc = new jsPDF();

    // --- Header ---
    doc.setFontSize(20);
    doc.text('SpeakSharp Session Report', 14, 22);

    // --- Session Metadata ---
    doc.setFontSize(12);
    try {
      const sessionDate = format(parseISO(session.created_at), 'MMMM do, yyyy');
      doc.text(`Date: ${sessionDate}`, 14, 32);
    } catch (e) {
      doc.text(`Date: ${session.created_at}`, 14, 32);
    }
    doc.text(`Duration: ${Math.round(session.duration / 60)} minutes`, 14, 42);

    // --- Analytics ---
    doc.setFontSize(16);
    doc.text('Vocal Analytics', 14, 60);

    const analyticsData = [
      ['Metric', 'Value'],
      ['Speaking Pace (WPM)', session.wpm?.toString() || 'N/A'],
      ['STT Engine', formatEngineLabel(session)],
      ['Silence Percentage', formatOptionalNumber(session.pause_metrics?.silencePercentage, value => `${value.toFixed(1)}%`)],
      ['Short Pauses (0.5-1.5s)', formatOptionalNumber(session.pause_metrics?.transitionPauses, value => value.toString(), '0')],
      ['Long Pauses (>1.5s)', formatOptionalNumber(session.pause_metrics?.extendedPauses, value => value.toString(), '0')],
      ['Longest Pause', formatOptionalNumber(session.pause_metrics?.longestPause, value => `${value.toFixed(1)}s`)],
    ];

    autoTable(doc, {
      startY: 70,
      body: analyticsData,
      theme: 'striped',
      headStyles: { fillColor: [41, 128, 185] },
    });

    if (session.filler_words) {
      const tableData = getFillerTableData(session.filler_words);
      autoTable(doc, {
        startY: (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10,
        head: [['Filler Word', 'Frequency']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [22, 160, 133] },
      });
    }

    // --- Transcript ---
    doc.addPage();
    doc.setFontSize(16);
    doc.text('Transcript', 14, 22);
    doc.setFontSize(10);
    const transcriptLines = doc.splitTextToSize(session.transcript || 'No transcript available.', 180);
    doc.text(transcriptLines, 14, 32);

    // --- Footer & Watermark ---
    const pageCount = (doc.internal as unknown as jsPDFInternal).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      
      // Page Number
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);

      doc.setFontSize(10);
      doc.setTextColor(180, 180, 180);
      const watermarkText = 'Generated by SpeakSharp';
      const textWidth = doc.getTextWidth(watermarkText);
      doc.text(watermarkText, doc.internal.pageSize.width - textWidth - 14, doc.internal.pageSize.height - 10);
      
      // Reset color for other potential elements
      doc.setTextColor(0, 0, 0);
    }

    // Use a friendly filename: session_date_time_identifier.pdf
    const dateStr = format(parseISO(session.created_at), 'yyyyMMdd_HHmmss');
    const sanitizedIdentifier = identifier.replace(/[^a-zA-Z0-9]/g, '_');
    const filename = `session_${dateStr}_${sanitizedIdentifier}.pdf`;

    toast.info(`Saving as: ${filename}`, { id: 'pdf-gen-name' });

    // Use FileSaver.js (industry standard) for reliable cross-browser download
    const blob = doc.output('blob');
    saveAs(blob, filename);

    toast.success("PDF Downloaded!", { id: 'pdf-gen' });

    // --- E2E Verification Signal ---
    if (typeof window !== 'undefined') {
      document.body.setAttribute('data-pdf-token', 'watermarked');
      setTimeout(() => document.body.removeAttribute('data-pdf-token'), 5000);
    }
  } catch (error: unknown) {
    logger.error({
      error,
      sessionId: session.id,
      message: error instanceof Error ? error.message : String(error)
    }, '[pdfGenerator] Error in PDF generation');
    toast.error('Failed to generate PDF report. Please try again.', { id: 'pdf-gen' });
  }
};
